logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                orm:
                    jdbc:
                        bind: TRACE
mobilele:
    default:
        admin:
            pass: ${DEFAULT_ADMIN_PASS:topsecret}
    remember:
        me:
            key: ${REMEMBER_ME:topsecret}
open:
    exchange:
        rates:
            app_id: ${APP_ID:test}
            enabled: false
            host: openexchangerates.org
            path: /api/latest.json
            schema: https
            symbols: BGN,EUR
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD:}
        url: jdbc:mysql://localhost:3306/mobilele?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${MYSQL_USER:}
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB
    sql:
        init:
            mode: never
mail:
    mobilele: "mobilele@example.com"
    host: localhost
    port: 1025
    username: ${MAIL_USER:softuni}
    password: ${MAIL_PASSWORD:softuni}